import { pool } from "@workspace/db";
import { runMigrations } from "@workspace/db/migrate";

/**
 * Schema bootstrap for the api-server.
 *
 * As of P0.5, the canonical schema lives in `lib/db/src/schema/*` (Drizzle)
 * and the SQL migrations in `lib/db/drizzle/`. The api-server runs those
 * migrations on startup via `runMigrations()`.
 *
 * The legacy `ensure*` helpers below are kept for the few operations that
 * Drizzle migrations don't model yet:
 *   - session table (express-session / connect-pg-simple, not in Drizzle)
 *   - tour_config (Remotion tour overrides, not in Drizzle)
 *   - inbound_emails (IMAP listener, not in Drizzle)
 *   - legacy column backfills (e.g. users.n -> users.can_admin_access)
 *
 * The Drizzle migration generated by P0.5 covers users, signup_requests,
 * patients, records, record_definitions, record_images, audit_log,
 * feedback, api_tokens, saved_views, notifications, login_challenges,
 * radiology_images, analysis_datasets, analysis_runs, analysis_variables.
 * As more tables move into the Drizzle schema, drop the corresponding
 * ensure* here.
 */

export async function runAllMigrations(): Promise<void> {
  await runMigrations();
}

export async function ensureSessionTable(): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS "session" (
      "sid" varchar NOT NULL COLLATE "default",
      "sess" json NOT NULL,
      "expire" timestamp(6) NOT NULL,
      CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE
    ) WITH (OIDS=FALSE);
    CREATE INDEX IF NOT EXISTS "IDX_session_expire" ON "session" ("expire");
  `);
}

/** Backfill: legacy "n" column -> "can_admin_access". Safe to re-run. */
export async function ensureUsersLegacyBackfills(): Promise<void> {
  await pool.query(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'n'
      ) THEN
        UPDATE "users" SET "can_admin_access" = "n"
        WHERE "n" IS TRUE AND "can_admin_access" IS DISTINCT FROM "n";
      END IF;
    END $$;
  `);
}

export async function ensureTourConfigTable(): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS "tour_config" (
      "id" integer PRIMARY KEY,
      "config" jsonb NOT NULL DEFAULT '{}'::jsonb
    );
    INSERT INTO "tour_config" ("id", "config")
      VALUES (1, '{"defaultSource":"animated","steps":{}}'::jsonb)
      ON CONFLICT ("id") DO NOTHING;
  `);
}

export async function ensureInboundEmailTable(): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS "inbound_emails" (
      "id" serial PRIMARY KEY,
      "sender" text NOT NULL,
      "recipient" text NOT NULL,
      "subject" text NOT NULL DEFAULT '(no subject)',
      "body_text" text NOT NULL DEFAULT '',
      "body_html" text,
      "message_id" text,
      "in_reply_to" text,
      "received_at" timestamp NOT NULL DEFAULT now(),
      "replied_at" timestamp
    );
    CREATE INDEX IF NOT EXISTS "IDX_inbound_received" ON "inbound_emails" ("received_at");
  `);
}

/**
 * @deprecated use runAllMigrations() — kept for backwards compatibility with
 * the old startup chain. The `authTables` portion is now a no-op since the
 * Drizzle migration covers every table it used to create.
 */
export async function ensureAuthTables(): Promise<void> {
  // No-op. Tables are now created by runAllMigrations().
}

/** Run every bootstrap step in the order they were historically executed at startup. */
export async function ensureAllTables(): Promise<void> {
  await runAllMigrations();
  await ensureSessionTable();
  await ensureUsersLegacyBackfills();
  await ensureTourConfigTable();
  await ensureInboundEmailTable();
}